# Generated by Django 3.0.3 on 2020-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Anaesthesiology', 'Anaesthesiology'), ('Apparel', 'Apparel'), ('Cardiology', 'Cardiology'), ('Dental equipment and supplies', 'Dental equipment and supplies'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Laboratory', 'Laboratory'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Radiology', 'Radiology'), ('Sterilization', 'Sterilization'), ('Surgery', 'Surgery')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
