# Generated by Django 3.0.3 on 2020-02-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('streetAddress', models.CharField(max_length=200, null=True)),
                ('cityAddress', models.CharField(max_length=200, null=True)),
                ('stateAddress', models.CharField(max_length=200, null=True)),
                ('zipCode', models.CharField(max_length=10, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
