# Generated by Django 3.0.3 on 2020-02-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cityAddress',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='stateAddress',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='streetAddress',
            new_name='street',
        ),
        migrations.AddField(
            model_name='patient',
            name='medicalId',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
